[package]
name = "tinybvh-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.20.0", features = ["derive"] }
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"

[dev-dependencies]
approx = "0.5.1"
