[package]
name = "tinybvh-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.20.0", features = ["derive"] }
cxx = "1.0"
enumflags2 = "0.7.10"

[build-dependencies]
cxx-build = "1.0"
