name: Cargo Build & Test

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Rustup
        run: rustup update stable && rustup default stable
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
